- name: Create
  community.general.jenkins_job:
    config: "{{ lookup('file', 'tmp/job.xml') }}"
    name: "{{test}}"
    url: http://172.31.14.199:8080
    user: admin
    password: "{{jenkins_password}}"
  loop:
    - frontend

